### PR TITLE
chore(php): fix PHP 8.2 deprecations

### PR DESCRIPTION
**Pull request by jrmajor**

### CODE REVIEW

**Review by Ocramius — COMMENTED** [review]
LGTM :+1: 

@azjezz as mentioned in chat, would need this for https://github.com/Roave/BackwardCompatibilityCheck/pull/643

If you can do a release with it, I'll also do a release from my end :muscle:

**Comment by azjezz** [comment]
@Ocramius 8.2 build fails because https://github.com/Ocramius/PackageVersions/ doesn't support 8.2 yet 😆

**Comment by Ocramius** [comment]
I can fix that, gimme a sec (sitting in a meeting :-) )

**Comment by Ocramius** [comment]
Released: https://github.com/Ocramius/PackageVersions/releases/tag/2.6.0

**Comment by Ocramius** [comment]
I'll do a quick release of `roave/infection-static-analysis-plugin` too :)

**Comment by Ocramius** [comment]
Hmmmmmmmno, I already did: https://github.com/Roave/infection-static-analysis-plugin/releases/tag/1.23.0

**Comment by azjezz** [comment]
Yea, PSL was pinned to 1.13.x-dev for some reason, updating..

**Comment by azjezz** [comment]
ready 🎉

**Review by Ocramius — COMMENTED** [review]
Looking good! :ship:

**Review by azjezz — APPROVED** [review]

**Pull request merged**
