### PR TITLE
Backport static analysis fixes to 1.6

### PR DESCRIPTION
**Pull request by veewee**
Backported these fixes to resolve Type\shape() issues:

* https://github.com/azjezz/psl/commit/821391fe0539b2158efff4c72916d18d829be9a0
* https://github.com/azjezz/psl/commit/0118dbcd97660723af918999f0d4db4eca43292b

### CODE REVIEW

**Comment by veewee** [comment]
@azjezz  any clue on the failing unit test?
It only fails on mac for some reason, and it didn't change in versions above...
Looks like a rounding issue

```
1) Psl\Tests\Math\TanTest::testTan with data set #0 (-3.380515006246586, 5.0)
Failed asserting that -3.380515006246585 is identical to -3.380515006246586.

/Users/runner/work/psl/psl/tests/Psl/Math/TanTest.php:17

```

Should be "-3.380515006246586" on all versions though : https://3v4l.org/Bq0B4
My mac also states it is "-3.380515006246585". So might be a mac issue, but then again - it should fail on 2.x and 1.9.x as well

**Comment by azjezz** [comment]
I'm guessing this fails for PHP 7.4, but not +8.0? 🤔 no idea honestly.

If it's just this test case, we can suppress it for 1.6 branch.

**Comment by veewee** [comment]
Tested it on all php versions on Mac and got the same error.
Don't understand why it does work on never versions of PSL, since nothing changed to the code or test..


Will suppress it on this branch

**Review by azjezz — APPROVED** [review]

**Comment by azjezz** [comment]
@veewee can you release a new 1.6?

**Comment by veewee** [comment]
Done! Thanks.

**Comment by azjezz** [comment]
@veewee the MacOS issue exists in 2.0.x branch as well, showed up now after i ran CI :/

**Comment by veewee** [comment]
Probably related with newer Mac versions and underlying libraries then... We could round the result to 5 digits in the test cases or report it to internals? The rounding issue doesn't seem that dramatic to me though. But then again: I haven't used cos,sin,tan in ages

**Comment by jrmajor** [comment]
@veewee There's a dedicated PHPUnit method for this use case: `assertEqualsWithDelta()`. Unfortunately, there's nothing like `assertSameWithDelta()`.

Edit: looking at the source code, I think `assertEquals()` has a default delta: https://github.com/sebastianbergmann/comparator/blob/926815b015c4c459f8ec5185328eb34ade07c51f/src/DoubleComparator.php#L53-L55.

**Comment by azjezz** [comment]
> assertEqualsWithDelta()

we shouldn't use this, the float value is correct, something weird is going on in MacOs that results in incorrect result.

**Pull request merged**
