### PR TITLE
chore: remove all references to callable, replace by closure

### PR DESCRIPTION
**Pull request by azjezz**
Signed-off-by: azjezz <azjezz@protonmail.com>

### CODE REVIEW

**Comment by veewee** [comment]
Any specific reason for accepting a less broad set of callbacks?

**Comment by bendavies** [comment]
@azjezz any reason for this change? making upgrading quite a chore :)

**Comment by bendavies** [comment]
i guess it's because of  first-class callables in 8.1

```php
map($api->getAll($params), [PostingPeriod::class, 'fromArray']);
```
becomes

```php
map($api->getAll($params), PostingPeriod::fromArray(...));
```

**Comment by bendavies** [comment]
although we did have some callable classes (with `__invoke`) which we now can't use so nicely.
that needs:

before:
```php
map($value, $this->foo);
```
after:

```php
map($value, Closure::fromCallable($this->foo));
```
or

```php
map($value, $this->foo->__invoke(...));
```

because this doesn't work:
```php
map($value, $this->foo(...));
```

not very nice

**Comment by bendavies** [comment]
i'm an idiot.
this works:
```php
map($value, ($this->foo)(...));
```

**Comment by azjezz** [comment]
The reasoning behind this change is in revolt-php, which uses Closure for all callbacks within the event loop, we can use Closure in async related functions, but that would be an inconsistency that i would rather avoid.

**Pull request merged**
