### PR TITLE
Indicate support for PHP 8.3

### PR DESCRIPTION
**Pull request by gsteel**

### CODE REVIEW

**Comment by gsteel** [comment]
Is it worth going through test failures on MacOS with…

```php
if (is_darwin()) {
    static::markTestSkipped('MacOS has floating point issues (And issues with ext-intl)');
}
```

It would make running the mutation tests easier locally… ?

**Comment by veewee** [comment]
Thanks for the PR! Much appreciated.

About:
> ```
> if (is_darwin()) {
>     static::markTestSkipped('MacOS has floating point issues (And issues with ext-intl)');
> }
> ```

I've fixed those together with the infection issues in PR https://github.com/azjezz/psl/pull/427 but it isn't merged yet.
Looking at the errors in github actions, I think they are all covered. 
So it should be fine after that one is merged.

**Comment by gsteel** [comment]
👍 Thanks @veewee

**Comment by veewee** [comment]
@gsteel That PR that was blocking the tests has been merged. Can you rebase from the `next` branch?

**Comment by veewee** [comment]
Thanks again!

**Pull request merged**
