### PR TITLE
Added repro for #212

### PR DESCRIPTION
**Pull request by zerkms**
Because I removed a global suppression there would be errors around the codebase, but I think those should addressed particularly in every specific case.

### CODE REVIEW

**Comment by azjezz** [comment]
Hm, this doesn't seem to be failing 🤔

**Comment by azjezz** [comment]
🙃 the static analysis configuration doesn't include `tests/static-analysis` could you please add it?

**Comment by zerkms** [comment]
@azjezz it's because

```
static-analysis:
	php tools/psalm/vendor/bin/psalm -c tools/psalm/psalm.xml --show-info=true --no-cache
	php tools/psalm/vendor/bin/psalm -c tools/psalm/psalm.xml tests/static-analysis --no-cache
```

the first command fails, so the second is not even run.

If run separately it's:

```
I have no name!@d0576c8e7d27:/app$ php tools/psalm/vendor/bin/psalm -c tools/psalm/psalm.xml tests/static-analysis --no-cache
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░

To whom it may concern: Psalm cannot detect unused classes, methods and properties
when analyzing individual files and folders. Run on the full project to enable
complete unused code detection.

ERROR: RedundantCondition - ../../tests/static-analysis/Type/shape.php:12:15 - Type array<array-key, mixed> for $data is always array (see https://psalm.dev/122)
    ], true)->assert($data);


------------------------------
1 errors found
------------------------------

Checks took 0.99 seconds and used 166.654MB of memory
Psalm was unable to infer types in the codebase
```

**Comment by azjezz** [comment]
yea, i think we should make it into just one command and add the tests to psalm config

**Comment by zerkms** [comment]
@azjezz see another commit

**Comment by azjezz** [comment]
ref: https://github.com/vimeo/psalm/issues/6573

**Comment by azjezz** [comment]
now that we know the source of this issue, i think it's safe to close it.

The best solution for you as a user right now is to suppress redundant conditions until this is fixed in Psalm.

**Pull request closed without merging**
