### PR TITLE
replace `@use` annotation by `@see`

### PR DESCRIPTION
**Pull request by b1rdex**
`@use` is used in psalm/phpstan for generic traits: https://psalm.dev/docs/annotating_code/templated_annotations/#template-inheritance

### CODE REVIEW

**Comment by azjezz** [comment]
Hey @b1rdex, thank you for the PR; but i want to understand the reason behind it, we use `@use` in multiple places, not just here, so if we are replacing it, we should replace it everywhere.

does phpstan complain about this? as psalm doesn't seem to do that currently.

**Comment by b1rdex** [comment]
I think this is a bug introduced during refactoring. Check out the full commit diff that brought the @use.
Also, there is no point in replacing @see with @use as it isn’t supported by phpstorm or any other phpdoc reader. 

Отправлено с iPhone

**Comment by azjezz** [comment]
@b1rdex can you please rebase this on 1.6.x and replace all other use cases of `@use` by `@see`?

**Comment by b1rdex** [comment]
@azjezz I don't see any other `@use` usages. Could you please verify?

**Comment by azjezz** [comment]
correct, i think we are already using `@see` everywhere else.

thank you 👍

**Pull request merged**
