### PR TITLE
Added positive int as type

### PR DESCRIPTION
**Pull request by michaelpetri**
Nothing special just added support for positive integers, would create another patch for natural integers afterwards.

### CODE REVIEW

**Comment by michaelpetri** [comment]
`make coding-standard-fix` always "fixes" my psalm-return annotation from:
```php
    /**
     * @param mixed $value
     *
     * @throws CoercionException
     *
     * @psalm-return positive-int
     */
    public function coerce($value): int
```
to
```php
    /**
     * @param mixed $value
     *
     * @throws CoercionException
     *
     * @return positive-int
     */
    public function coerce($value): int
```

any idea?

**Comment by azjezz** [comment]
That's intentional, we don't use psalm- prefix :)

**Comment by michaelpetri** [comment]
Removed psalm prefix, can you share some insights why you don't use them?

**Comment by azjezz** [comment]
annotations which we don't prefix with psalm are also supported by phpstan, and phpstorm ( recently started supporting lowercase-string, positive-int, no-return .. etc ), so there's no need for the use of the `psalm-` prefix IMHO.

**Review by azjezz — APPROVED** [review]
Thank you @michaelpetri

**Pull request merged**
